// <auto-generated />
using System;
using Dengue.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dengue.Infrastructure.Migrations
{
    [DbContext(typeof(DengueDbContext))]
    partial class DengueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dengue.Domain.Entities.DengueAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Casos")
                        .HasColumnType("int");

                    b.Property<double>("CasosEst")
                        .HasPrecision(18, 4)
                        .HasColumnType("float(18)");

                    b.Property<DateTime>("DataIniSE")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ew")
                        .HasColumnType("int");

                    b.Property<int>("Ey")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<int?>("NivelInc")
                        .HasColumnType("int");

                    b.Property<int?>("NotifAccumYear")
                        .HasColumnType("int");

                    b.Property<double?>("PInc100k")
                        .HasPrecision(18, 6)
                        .HasColumnType("float(18)");

                    b.Property<double?>("PRt1")
                        .HasPrecision(18, 6)
                        .HasColumnType("float(18)");

                    b.Property<double?>("Pop")
                        .HasPrecision(18, 4)
                        .HasColumnType("float(18)");

                    b.Property<int?>("Receptivo")
                        .HasColumnType("int");

                    b.Property<double?>("Rt")
                        .HasPrecision(18, 6)
                        .HasColumnType("float(18)");

                    b.Property<int?>("Transmissao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ew", "Ey")
                        .IsUnique();

                    b.ToTable("DengueAlerts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
